development:
  adapter: mysql2
  xa: false
  encoding: utf8
  username: root
  password:
  database: shopify_registry_dev
test:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: shopify_registry_test
